on:
  push:
    branches: ["master"]

jobs:
  depoy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir gh-pages
      - run: cp favicon.ico gh-pages
      - uses: ./
        with:
          format: html
          output: ./gh-pages/index.html
      - run: "pwd; ls"
      - uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_DIR: gh-pages
          PUBLISH_BRANCH: gh-pages
