name: Deploy 🚀

on:
  push:
    branches: ["main", "deploy-test"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir gh-pages
      - run: cp favicon.ico gh-pages
      - uses: ./
        with:
          format: html
          output: ./gh-pages/index.html
      - run: "find ./gh-pages"
      # https://github.com/peaceiris/actions-gh-pages/releases/tag/v3.8.0
      - uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: gh-pages
